name: cryptoPortfolio
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-inline=0.1.2
  - numpy=1.20.3
  - numpy-base=1.20.3
  - pandas=1.3.2
  - pip=21.0.1
  - plotly=5.3.0
  - python=3.8.11
  - python-cufflinks
  - python-dateutil=2.8.2
  - python-tzdata=2021.1
  - python_abi=3.8
  - streamlit=0.84.1
  - pip:
    - pycoingecko==2.2.0
